schemaVersion: 1.1.0
locale: "en"
groupings:
  - title: "Deploy Nginx service using Container Instances"
    variables:
    - region
    - compartment_ocid

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to create all resources
    required: true
